<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resizable_react-resizable-handle react_781f9e</name>
   <tag></tag>
   <elementGuidId>c52d87fc-e55a-4773-a5f5-7a525165dbdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resizable']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#resizable > span.react-resizable-handle.react-resizable-handle-se</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f9f0477-ef69-40db-8623-89e57fca91c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-resizable-handle react-resizable-handle-se</value>
      <webElementGuid>f66eb1aa-83b8-4e00-9452-3552128e3b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resizable&quot;)/span[@class=&quot;react-resizable-handle react-resizable-handle-se&quot;]</value>
      <webElementGuid>2b81c769-dc15-4f41-b057-f80892ce4edb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resizable']/span</value>
      <webElementGuid>3a31fcd1-6f67-441f-b807-144c3c73db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>61589ed8-8de5-4844-8e59-e4a9a5565452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
