<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Acceptable b</name>
   <tag></tag>
   <elementGuidId>500ea0ce-447f-4258-aeb7-808f5624edb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='acceptable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acceptable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>73101be7-30e8-4a24-8cf1-f190ef313476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptable</value>
      <webElementGuid>fea87917-3107-4eb1-b44a-cd4ae34ed1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box mt-4 ui-draggable ui-draggable-handle</value>
      <webElementGuid>0dbdd0ae-2d2d-438d-b54e-1db733261f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acceptable</value>
      <webElementGuid>03e9961e-d78e-4015-b8cd-4d49d72e04ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptable&quot;)</value>
      <webElementGuid>8cc08e61-6459-439f-a6cd-7c9614e39803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='acceptable']</value>
      <webElementGuid>22cbedc0-b769-49cb-8037-f8bdb96b618f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='acceptDropContainer']/div/div</value>
      <webElementGuid>0745e846-6cf7-485e-8cd6-aa5ff8189d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag me'])[1]/following::div[5]</value>
      <webElementGuid>6e10a645-39d2-46ed-88ae-485f5c909639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Droppable'])[2]/following::div[9]</value>
      <webElementGuid>83d1268d-dfbb-4bf4-8396-fcfef7677a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag Me'])[1]/preceding::div[3]</value>
      <webElementGuid>95336045-9924-42ba-9965-2e976b278f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acceptable']/parent::*</value>
      <webElementGuid>f613887d-11fe-4fcf-9e06-83a58d1b966b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div</value>
      <webElementGuid>6ddb4388-7e4a-462f-a00c-cc5882405aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'acceptable' and (text() = 'Acceptable' or . = 'Acceptable')]</value>
      <webElementGuid>1a29fbfd-bddc-4151-9709-e4d2a3c67bd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
