<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Color Change</name>
   <tag></tag>
   <elementGuidId>a922ffe8-834b-4371-a651-c4f8545b68d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#colorChange</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='colorChange']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29665290-fd2a-46d0-873c-4ba25e297436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>colorChange</value>
      <webElementGuid>de4a188d-5960-40db-8835-a09b7c50b520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7860b098-2abb-4de7-95bd-f96781fa2502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4 text-danger btn btn-primary</value>
      <webElementGuid>221147a6-1762-4c90-a75f-adbbc18fa4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Color Change</value>
      <webElementGuid>53478758-2e68-42de-91b8-7eef1b8c33e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;colorChange&quot;)</value>
      <webElementGuid>7ce22137-b89d-4e56-b257-e3c1204603af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='colorChange']</value>
      <webElementGuid>a9b9296b-ef50-480a-9468-486312143b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>5d3758ab-d5a3-4987-bfd5-87b828590aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Will enable 5 seconds'])[1]/following::button[1]</value>
      <webElementGuid>1dce6709-3e55-42f7-9eb2-4e40d4a8d65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dynamic Properties'])[2]/following::button[2]</value>
      <webElementGuid>c4e25715-0679-4e2c-8001-6ccb826957ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visible After 5 Seconds'])[1]/preceding::button[1]</value>
      <webElementGuid>da6a4b46-10ff-4331-9282-8ce98f5dcf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::button[2]</value>
      <webElementGuid>29462a25-c3ea-4722-8fec-dc25ffb507b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Color Change']/parent::*</value>
      <webElementGuid>a440cdac-9216-449d-8649-dcbac5003c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7a4f1c48-bdc7-41f2-81f3-920459dd5ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'colorChange' and @type = 'button' and (text() = 'Color Change' or . = 'Color Change')]</value>
      <webElementGuid>3a94bff1-8597-44f4-a3e0-39bcca0a8ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
