<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Small modal</name>
   <tag></tag>
   <elementGuidId>ceb71826-f9aa-4e7c-9689-a71585c30970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='showSmallModal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#showSmallModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79449c46-8f4d-4543-b65b-e2beda1d32c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showSmallModal</value>
      <webElementGuid>3d60d28c-baf7-42b7-af17-1acff1abd4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>066aa1ba-be77-4140-8fc1-8519afd9566a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-4 mt-2 btn btn-primary</value>
      <webElementGuid>650f0519-9a6a-43a7-83f7-f8c91a16fe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Small modal</value>
      <webElementGuid>a8f42851-c604-4ea2-b3bc-fedc6220a2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showSmallModal&quot;)</value>
      <webElementGuid>92702242-ae37-4fe4-ba21-1e015f88ebcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='showSmallModal']</value>
      <webElementGuid>68a34dd1-4889-4db3-81e2-9f2ec593bbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalWrapper']/div/button</value>
      <webElementGuid>4b46dc06-91f7-46f7-a914-b917ff737e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click on button to see modal'])[1]/following::button[1]</value>
      <webElementGuid>d5049c7e-3200-4716-b3d5-4442cf17deb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modal Dialogs'])[2]/following::button[1]</value>
      <webElementGuid>45d5ba26-b51e-4dd2-ab4f-083392fcf774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Large modal'])[1]/preceding::button[1]</value>
      <webElementGuid>0af654e6-a31d-478f-8c9d-273c676b5083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::button[2]</value>
      <webElementGuid>c3c7232c-fe72-4d49-bcfa-74ab1597d9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Small modal']/parent::*</value>
      <webElementGuid>9bbe831c-f88f-4c94-afba-2c5c6fc01824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>0729aae1-7ae1-4346-b8be-5f6c74753e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'showSmallModal' and @type = 'button' and (text() = 'Small modal' or . = 'Small modal')]</value>
      <webElementGuid>e1265268-2a92-4381-8181-f3188ec3deda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
