<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_xpath test</name>
   <tag></tag>
   <elementGuidId>6f1c1d80-5135-4c46-a2c3-01e310ba01cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='linkWrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#linkWrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53b2dba7-1316-4751-8656-4a84a779481f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>linkWrapper</value>
      <webElementGuid>2161117d-1ce7-4879-95c3-61faaa3a2f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LinksFollowing links will open new tabHomeHomeoYIqcFollowing links will send an api callCreatedNo ContentMovedBad RequestUnauthorizedForbiddenNot Found</value>
      <webElementGuid>c1bd3355-f50c-4789-956a-956e1df31320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;linkWrapper&quot;)</value>
      <webElementGuid>909b4420-b4b4-4fd3-aa77-a1584a9a8008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='linkWrapper']</value>
      <webElementGuid>23154d5b-5d67-4599-b5e3-f235fcd723a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/div[2]</value>
      <webElementGuid>c0abeac7-868a-43d4-9d22-616e2dfbbd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[4]</value>
      <webElementGuid>6d04fcc0-a704-4a08-a312-f01841956a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[4]</value>
      <webElementGuid>b82a1101-6c7b-4d94-a5b4-6879070ea2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>94ee1b12-ba00-46d8-8c96-aac76617bb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'linkWrapper' and (text() = 'LinksFollowing links will open new tabHomeHomeoYIqcFollowing links will send an api callCreatedNo ContentMovedBad RequestUnauthorizedForbiddenNot Found' or . = 'LinksFollowing links will open new tabHomeHomeoYIqcFollowing links will send an api callCreatedNo ContentMovedBad RequestUnauthorizedForbiddenNot Found')]</value>
      <webElementGuid>f2c2da42-5b1b-4460-9409-794908768cf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
