<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Eight</name>
   <tag></tag>
   <elementGuidId>9a222cc7-b252-404d-8cde-aaaf616d2a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-tabpane-grid']/div/div/div[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d219c0c-943e-43ff-81a3-a2a5eec24c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action</value>
      <webElementGuid>3b4c402e-e6d0-4b22-aeea-f4cea36cdefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eight</value>
      <webElementGuid>ac8828c2-7727-4218-a795-f67a81a422ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-tabpane-grid&quot;)/div[@class=&quot;grid-container mt-4&quot;]/div[@class=&quot;create-grid&quot;]/div[@class=&quot;list-group-item list-group-item-action&quot;]</value>
      <webElementGuid>fac1dd9e-27c2-472c-a444-4fd2289b436a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo-tabpane-grid']/div/div/div[8]</value>
      <webElementGuid>14678000-c257-4dbc-8ace-8b44e0a2cc36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seven'])[1]/following::div[1]</value>
      <webElementGuid>50d4d42b-15df-4f5f-8287-6ed38befa4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Six'])[2]/following::div[2]</value>
      <webElementGuid>ced28022-0d8e-49d8-8460-7bc765e5c31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nine'])[1]/preceding::div[1]</value>
      <webElementGuid>8265efd1-4b1a-46f0-9921-a75a9fbcc122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[14]</value>
      <webElementGuid>37ca3d2a-a95f-4247-b272-47f909955748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eight']/parent::*</value>
      <webElementGuid>bef41b26-064f-4f68-8bd0-4aa35254df1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>fca358fc-2b71-43e0-b975-714d4c2cc372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Eight' or . = 'Eight')]</value>
      <webElementGuid>acd757de-f6c6-4c6a-8041-70e1b1f0aa78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
