<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Two</name>
   <tag></tag>
   <elementGuidId>c36ca7b0-5f86-4615-a332-4e09f05c2ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-tabpane-grid']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84e24cda-abc6-4972-a053-c4a7573bf847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item list-group-item-action</value>
      <webElementGuid>e4630da7-3c2d-46ce-99bf-bf4cd677fa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Two</value>
      <webElementGuid>c4f4f4d9-ffff-46d8-870e-dccf5fd7636c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-tabpane-grid&quot;)/div[@class=&quot;grid-container mt-4&quot;]/div[@class=&quot;create-grid&quot;]/div[@class=&quot;list-group-item list-group-item-action&quot;]</value>
      <webElementGuid>3e176eed-2dbf-4421-828f-44b60aa1b595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='demo-tabpane-grid']/div/div/div[2]</value>
      <webElementGuid>acb2666d-1161-40ba-9fa0-183bc36f9b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One'])[2]/following::div[1]</value>
      <webElementGuid>3bd3f458-03f9-4999-b1a2-90dcd431b783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Six'])[1]/following::div[5]</value>
      <webElementGuid>a5ea9dbb-72f0-4551-8d39-cb7ea65bf65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Three'])[2]/preceding::div[1]</value>
      <webElementGuid>78446918-24de-4d16-9d9f-a10ad116dcc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Four'])[2]/preceding::div[2]</value>
      <webElementGuid>ead9893d-99d8-4840-bf4c-2eff55b0118e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>5d9862e8-71c6-466f-b7e7-fe8861ed42dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Two' or . = 'Two')]</value>
      <webElementGuid>f164d258-91d6-4679-99eb-c33411784d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
