<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Slider_range-slider range-slider--primary</name>
   <tag></tag>
   <elementGuidId>7481f7f5-8084-4e59-b235-9211c52fc2ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type='range']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a806c907-6319-46ad-b04d-24c268a80393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>range</value>
      <webElementGuid>7bc5f312-8919-4ccf-9c09-28cea485da90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>range-slider range-slider--primary</value>
      <webElementGuid>e976e17f-1ca4-4cd2-a29c-4b9d021cfd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7676794e-af8a-4826-8af6-ff5ba2ffe428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>850918b4-6466-4a34-a954-d9700fd2d459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>e804c9d8-4190-43cf-a3af-0534596553a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sliderContainer&quot;)/div[@class=&quot;col-9&quot;]/span[@class=&quot;range-slider__wrap&quot;]/input[@class=&quot;range-slider range-slider--primary&quot;]</value>
      <webElementGuid>a9512e0a-6332-433f-9593-87df60a9accf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='35']</value>
      <webElementGuid>f87553ed-37c4-4a8c-acd7-804380efcb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sliderContainer']/div/span/input</value>
      <webElementGuid>6e0ed55b-f4ff-48f6-82e5-44c4fab190f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fe096480-1d81-4698-b732-0f69f726d771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'range']</value>
      <webElementGuid>17c35794-2d30-420e-8054-8d0ad53c2c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
