<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Only X</name>
   <tag></tag>
   <elementGuidId>96a2283f-f92c-4706-affe-ea25f98a078c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='restrictedX']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#restrictedX</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3194cc8-33db-4a17-a385-58cfb857e674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>restrictedX</value>
      <webElementGuid>a8b3c105-40e2-4576-8d4e-c09817fcc833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box ui-draggable ui-draggable-handle</value>
      <webElementGuid>e06350b8-c194-47bc-8b44-6736c40a51ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Only X</value>
      <webElementGuid>6870d4f8-4814-4027-8608-800e346727e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;restrictedX&quot;)</value>
      <webElementGuid>78be4911-c2b3-49ce-bf33-5b331ad31fa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='restrictedX']</value>
      <webElementGuid>015fb80e-7501-47d1-9930-be8d045b6909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggableExample-tabpane-axisRestriction']/div/div</value>
      <webElementGuid>e897e16d-7944-45a3-890c-890459b9efe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag me'])[1]/following::div[3]</value>
      <webElementGuid>a3e935e6-dc1e-440b-8465-3fa4028f4945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dragabble'])[2]/following::div[6]</value>
      <webElementGuid>40cdf917-4f77-431e-bdf2-85916470aed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only Y'])[1]/preceding::div[1]</value>
      <webElementGuid>941b3b4d-3266-4f10-97da-b9fd592a5d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Only X']/parent::*</value>
      <webElementGuid>7e8767c4-8f95-454e-adfe-1cd813660b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>518a04ad-d953-4327-8b1c-8a1f55ddfa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'restrictedX' and (text() = 'Only X' or . = 'Only X')]</value>
      <webElementGuid>a9c77bd4-1b53-4fe8-996d-e9e499e043c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
