<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My cursor is at bottom</name>
   <tag></tag>
   <elementGuidId>c716634a-4952-4255-911d-003f4c3fc1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cursorBottom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cursorBottom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12efb698-c446-4768-8ace-5d78899bebd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cursorBottom</value>
      <webElementGuid>06ac1d53-5518-41a9-af8d-1c1cbcdfb91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drag-box ui-draggable ui-draggable-handle</value>
      <webElementGuid>1bf6372e-2f52-4c8c-a7c8-b8823041accd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My cursor is at bottom</value>
      <webElementGuid>dd2aa17c-0b07-4d0b-8c1f-316369ab18dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cursorBottom&quot;)</value>
      <webElementGuid>44598536-3523-41c4-88c5-a8422fd2ab6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cursorBottom']</value>
      <webElementGuid>ea5b207d-2495-456f-9f56-1b009dc24b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='draggableExample-tabpane-cursorStyle']/div/div[3]</value>
      <webElementGuid>4644b08e-d7a7-4a2c-b202-67536ec9f2f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My cursor is at top left'])[1]/following::div[1]</value>
      <webElementGuid>a4cdffd8-927b-4358-af17-9f1f1cacf4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I will always stick to the center'])[1]/following::div[2]</value>
      <webElementGuid>b1c4ec6a-1983-433a-9042-0d6d3a606ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2013-2020 TOOLSQA.COM | ALL RIGHTS RESERVED.'])[1]/preceding::div[13]</value>
      <webElementGuid>29af554b-b220-4f08-b03f-4b4866a04f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]</value>
      <webElementGuid>e141d9a2-00a1-4732-af44-a256605add00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cursorBottom' and (text() = 'My cursor is at bottom' or . = 'My cursor is at bottom')]</value>
      <webElementGuid>e980ce68-0120-448a-8ee6-88b17e707e76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
