<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nested Frames_frame1</name>
   <tag></tag>
   <elementGuidId>38641d5a-e7f3-471f-b420-13d8dfe5dacc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='frame1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frame1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cc5edf5e-ce2f-4e7e-939c-40f06f847015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/sampleiframe</value>
      <webElementGuid>25de8ff6-2a5f-49be-87c2-2cb5802d7335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame1</value>
      <webElementGuid>d2443c4e-944e-4b6d-b721-1fcf78a32cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500px</value>
      <webElementGuid>c5e6fb31-9339-4aa8-bdf1-a528a3eec371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>350px</value>
      <webElementGuid>dbfdd49f-4a68-44aa-aa03-6b04a0f7efd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame1&quot;)</value>
      <webElementGuid>5a555c7f-7182-4725-81dd-072be52d9c86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='frame1']</value>
      <webElementGuid>853e7482-ae3f-4bb7-add5-2ed7209168ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frame1Wrapper']/iframe</value>
      <webElementGuid>b15008cb-1f25-4fab-b14f-99f2cabaaf69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>7a7c883b-9bcc-40c2-9e3f-549412018d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/sampleiframe' and @id = 'frame1']</value>
      <webElementGuid>d58266c3-93e8-409e-a1fd-9cc4294981a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
