<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_This is a sample page</name>
   <tag></tag>
   <elementGuidId>1307c358-dfbf-40d5-9376-b813ce9a0cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sampleHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='sampleHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>22f04a0c-e9a0-4b05-9997-753a89bb2e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sampleHeading</value>
      <webElementGuid>79c94ce3-2a8a-4649-8171-540c7686ce75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a sample page</value>
      <webElementGuid>3593f4b5-621f-4367-9af1-4f687cdb24fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sampleHeading&quot;)</value>
      <webElementGuid>b942a54c-3b68-47ca-8170-60c1b5fe21bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='sampleHeading']</value>
      <webElementGuid>e40b98a2-2664-46f8-8add-99ca9f31732e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a sample page']/parent::*</value>
      <webElementGuid>78d0f5be-4e3a-4572-a552-2dc0c72e0c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>12eaef35-2188-4066-8440-3ad371bd3b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'sampleHeading' and (text() = 'This is a sample page' or . = 'This is a sample page')]</value>
      <webElementGuid>e87ed8fc-a428-4e2d-99a7-e15d3c55c134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
