<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_This is a sample page</name>
   <tag></tag>
   <elementGuidId>47b135f6-e0d2-4793-b7bb-676472beef52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sampleHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='sampleHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>140c0245-6b64-433f-b1a8-d7641991ae45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sampleHeading</value>
      <webElementGuid>1ff56b23-73c1-4a33-beca-fcf27fdef2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a sample page</value>
      <webElementGuid>b889d6fb-e04c-479b-b0c3-a7569b7a6551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sampleHeading&quot;)</value>
      <webElementGuid>03cdc511-51e4-4af9-b12d-2bd5c16bd2a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='sampleHeading']</value>
      <webElementGuid>ad4bd9cc-6b59-4988-ba9e-0d01c9e8bf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a sample page']/parent::*</value>
      <webElementGuid>a6f1aa96-43e0-4599-a950-5d94cb746472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3c125bf7-71db-4599-8730-61b972cb30f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'sampleHeading' and (text() = 'This is a sample page' or . = 'This is a sample page')]</value>
      <webElementGuid>8d437eb9-3a25-4347-a229-5c0de81710ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
